version: "3.3"

services:
    # frontend (Nuxtjs)
    web:
        image: node:19

        user: node

        environment:
            - NODE_ENV=${NODE_ENV}

        working_dir: /usr/src/app

        volumes:
            - ./app/web:/usr/src/app

        command: bash -c "chown -R node:node /usr/src/app && yarn && yarn dev"

        ports:
            - 3000:3000

        networks:
            - app_net

        restart: on-failure

        depends_on:
            - api

    # backend (Nestjs)
    api:
        build: app/api

        env_file:
            - .env

        environment:
            - NODE_ENV=${NODE_ENV}

        volumes:
            - ./app/api:/usr/src/app

        command:  npm run start:dev

        networks:
            - app_net

        restart: on-failure

        ports:
            - 8000:8000

        depends_on:
            - db

    # Database (Postgres)
    db:
        image: postgres:12

        env_file:
            - .env

        container_name: db

        volumes:
            - db-data:/var/lib/postgresql/data

        restart: unless-stopped

        networks:
            - app_net

    # reverse proxy (nginx)
    nginx:
        image: nginx:latest

        environment:
            - NODE_ENV=${NODE_ENV}

        ports:
            - 80:80

        volumes:
            - ./config/default.conf:/etc/nginx/conf.d/default.conf

        networks:
            - app_net

        restart: on-failure

        depends_on:
            - api
            - web

networks:
    app_net:
        driver: bridge

volumes:
    db-data:
